stages:
  preprocess:
    cmd: |
      mkdir -p data/processed
      python src/preprocess.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: |
      mkdir -p models
      python src/train.py
    deps:
      - data/processed/train.csv
      - src/train.py
    outs:
      - models/model.pkl


  evaluate:
    cmd: python src/evaluate.py
    deps:
      - models/model.pkl
      - data/processed/test.csv
    outs:
      - experiments/results.json
    metrics:
      - metrics.json
    