stages:
  preprocess:
    cmd: python src/preprocess.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/train.csv
      - src/train.py
    outs:
      - models/model.pkl
    plots:
      - log.json:
          x: iteration
          y: train_accuracy
          title: "Training vs Testing Accuracy"
          template: simple

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - models/model.pkl
      - data/processed/test.csv
    outs:
      - experiments/results.json
    metrics:
      - metric.json
    