dataset: data/raw.csv

target: Survived

preprocessing:
  scale: True
  encode: True

model:
  type: RandomForestClassifier
  params:
    n_estimators: 5
    max_depth: 2
    random_state: 42

training:
  test_size: 0.2
  random_state: 42
